definitions:
  calltypes.ErrorResponse:
    properties:
      error:
        example: true
        type: boolean
      message:
        example: Error description
        type: string
    type: object
  calltypes.JSONResponse:
    properties:
      data: {}
      error:
        type: boolean
      message:
        type: string
    type: object
  calltypes.RegisterRequest:
    properties:
      active:
        example: 1
        type: integer
      email:
        example: user@example.com
        type: string
      firstName:
        example: John
        type: string
      lastName:
        example: Doe
        type: string
      password:
        example: securePassword123
        type: string
    type: object
info:
  contact: {}
  description: API for user authentication and token management.
  title: Authentication Service API
  version: "1.0"
paths:
  /getguid:
    get:
      description: Возвращает GUID авторизованного пользователя, который извлекается
        из access token'a
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/calltypes.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/calltypes.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Получить GUID текущего пользователя
      tags:
      - Authentication
  /logout:
    get:
      description: Разлогинивает пользователя и удаляет куки с токенами
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/calltypes.JSONResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/calltypes.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Разлогинить пользователя
      tags:
      - Authentication
  /provide/{id}:
    get:
      description: Генерирует и возвращает новую пару токенов для пользователя
      parameters:
      - description: User GUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/calltypes.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/calltypes.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/calltypes.ErrorResponse'
      summary: Получить новую пару токенов
      tags:
      - Authentication
  /refresh:
    get:
      description: Генерирует и возвращает обновлённую пару токенов для пользователя
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/calltypes.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/calltypes.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/calltypes.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Обновляет пару токенов
      tags:
      - Authentication
  /registrate:
    post:
      consumes:
      - application/json
      description: Создаёт новый аккаунт пользователя
      parameters:
      - description: User registration data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/calltypes.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/calltypes.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/calltypes.ErrorResponse'
      summary: Регистрация нового пользователя
      tags:
      - Authentication
swagger: "2.0"
